name: nexora
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  firebase_storage: ^13.2.0
  google_fonts: ^8.0.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png

