// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPl22hb_Bja70gjZlPhG48C0j9iWEk8Q',
    appId: '1:473855612979:web:6192de70f98778ec616b46',
    messagingSenderId: '473855612979',
    projectId: 'nexora-e87b0',
    authDomain: 'nexora-e87b0.firebaseapp.com',
    storageBucket: 'nexora-e87b0.firebasestorage.app',
    measurementId: 'G-J96W30CG1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMpOrmbFx8wWZblXFdFvfe9lXYFRN6mrI',
    appId: '1:473855612979:android:811256366eca2a51616b46',
    messagingSenderId: '473855612979',
    projectId: 'nexora-e87b0',
    storageBucket: 'nexora-e87b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlXiLLDmfBgR2OGHtF2vbno5p1mUr-oGo',
    appId: '1:473855612979:ios:ec374a6219865fa5616b46',
    messagingSenderId: '473855612979',
    projectId: 'nexora-e87b0',
    storageBucket: 'nexora-e87b0.firebasestorage.app',
    iosBundleId: 'com.example.nexora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlXiLLDmfBgR2OGHtF2vbno5p1mUr-oGo',
    appId: '1:473855612979:ios:ec374a6219865fa5616b46',
    messagingSenderId: '473855612979',
    projectId: 'nexora-e87b0',
    storageBucket: 'nexora-e87b0.firebasestorage.app',
    iosBundleId: 'com.example.nexora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBPl22hb_Bja70gjZlPhG48C0j9iWEk8Q',
    appId: '1:473855612979:web:099d9c8aaa287f69616b46',
    messagingSenderId: '473855612979',
    projectId: 'nexora-e87b0',
    authDomain: 'nexora-e87b0.firebaseapp.com',
    storageBucket: 'nexora-e87b0.firebasestorage.app',
    measurementId: 'G-MKE4X1EJQ4',
  );
}
